### ISSUE TITLE
undefined method `custom_properties' for #<APN::Notification:0x10f8919c> 

### ISSUE THREAD

**Issue by coneybeare** [PRX/apn_on_rails#33]
I have been getting this error lately…

``` bash
(in /home/webapps/[REDACTED]/releases/20110611190638)
** Invoke apn:notifications:deliver (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute apn:notifications:deliver
Finding notifications with a device in zone -1 (offset of UTC) (more-or-less)
Found 82103 notifications
rake aborted!
undefined method `custom_properties' for #<APN::Notification:0x10f8919c>
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/activemodel-3.0.7/lib/active_model/attribute_methods.rb:367:in `method_missing'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/activerecord-3.0.7/lib/active_record/attribute_methods.rb:46:in `method_missing'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bundler/gems/apn_on_rails-18f5d37397e3/lib/apn_on_rails/app/models/apn/notification.rb:59:in `apple_hash'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bundler/gems/apn_on_rails-18f5d37397e3/lib/apn_on_rails/app/models/apn/notification.rb:76:in `to_apple_json'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bundler/gems/apn_on_rails-18f5d37397e3/lib/apn_on_rails/app/models/apn/notification.rb:81:in `message_for_sending'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bundler/gems/apn_on_rails-18f5d37397e3/lib/apn_on_rails/app/models/apn/notification.rb:106:in `block (2 levels) in send_notifications'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bundler/gems/apn_on_rails-18f5d37397e3/lib/apn_on_rails/app/models/apn/notification.rb:105:in `each'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bundler/gems/apn_on_rails-18f5d37397e3/lib/apn_on_rails/app/models/apn/notification.rb:105:in `block in send_notifications'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bundler/gems/apn_on_rails-18f5d37397e3/lib/apn_on_rails/libs/connection.rb:60:in `open'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bundler/gems/apn_on_rails-18f5d37397e3/lib/apn_on_rails/libs/connection.rb:23:in `open_for_delivery'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bundler/gems/apn_on_rails-18f5d37397e3/lib/apn_on_rails/app/models/apn/notification.rb:104:in `send_notifications'
/home/webapps/[REDACTED]/releases/20110611190638/lib/tasks/apn.rake:46:in `block (3 levels) in <top (required)>'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `block in execute'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `block (2 levels) in top_level'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `block in top_level'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:2001:in `block in run'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/gems/rake-0.8.7/bin/rake:31:in `<top (required)>'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bin/rake:19:in `load'
/home/webapps/[REDACTED]/releases/20110611190638/vendor/bundle/ruby/1.9.1/bin/rake:19:in `<main>'
```

**Comment by coneybeare** [comment]
my mistake, wrong apn_on_rails fork.
