### ISSUE TITLE
Certificate issues which aren't found on other libraries

### ISSUE THREAD

**Issue by ivanyv** [PRX/apn_on_rails#41]
Hi,

Suddenly one of my apps that uses apn_on_rails stopped sending notifications.

APN::App.send_notifications fails with:

```
SSL_connect returned=1 errno=0 state=SSLv3 read server session ticket A: sslv3 alert certificate expired
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server session ticket A: sslv3 alert certificate expired
      from ~/.rbenv/versions/ree-1.8.7-2011.03/gems/apn_on_rails-0.5.1/lib/apn_on_rails/libs/connection.rb:59:in `connect'
```

The cert is valid until 2013, and it works fine if I use something like node-apn. I don't see anything obvious in the source code and I know little of SSL, so I'm at a loss.

**Comment by sushmasatish** [comment]
Hi,
  I am also encountering the similar issue with apn_on_rails(0.5.1). 

SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate revoked
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate revoked
    from /apn_on_rails-0.5.1/lib/apn_on_rails/libs/connection.rb:59:in `connect'
    from /apn_on_rails-0.5.1/lib/apn_on_rails/libs/connection.rb:59:in`open'
    from /apn_on_rails-0.5.1/lib/apn_on_rails/libs/connection.rb:23:in `open_for_delivery'
    from /apn_on_rails-0.5.1/lib/apn_on_rails/app/models/apn/app.rb:48:in`send_notifications_for_cert'
    from /apn_on_rails-0.5.1/lib/apn_on_rails/app/models/apn/app.rb:36:in `send_notifications'

**Comment by treeder** [comment]
Did either of you figure out what was causing this issue?

**Comment by rmatesic** [comment]
I am receiving the same error too 

<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server session ticket A: sslv3 alert certificate revoked>

Was anyone able to figure this one out? Some push notifications do go out, but every now and then they stop working.

**Comment by kayzee** [comment]
Having the same issue.  The best doc I could find is http://railsapps.github.com/openssl-certificate-verify-failed.html

My server is running on Ubuntu 10.04, so I plan on creating a new dev server with Ubuntu 12.04 to see if that resolves the problem, but otherwise I'm stumped as well.

**Comment by britg** [comment]
Did yall ever find a solution to this problem? I just started encountering it randomly as well.
